"""first migration

Revision ID: c21a2285ca5c
Revises:
Create Date: 2023-11-23 16:49:38.322287

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c21a2285ca5c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dummy_model",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dummy_model_id"), "dummy_model", ["id"], unique=False)
    op.create_index(op.f("ix_dummy_model_name"), "dummy_model", ["name"], unique=True)
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_id"), "organizations", ["id"], unique=False)
    op.create_index(
        op.f("ix_organizations_name"),
        "organizations",
        ["name"],
        unique=True,
    )
    op.create_table(
        "advisers",
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_advisers_external_id"),
        "advisers",
        ["external_id"],
        unique=True,
    )
    op.create_index(op.f("ix_advisers_id"), "advisers", ["id"], unique=False)
    op.create_index(op.f("ix_advisers_name"), "advisers", ["name"], unique=False)
    op.create_table(
        "distributors",
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_distributors_external_id"),
        "distributors",
        ["external_id"],
        unique=True,
    )
    op.create_index(op.f("ix_distributors_id"), "distributors", ["id"], unique=False)
    op.create_index(
        op.f("ix_distributors_name"),
        "distributors",
        ["name"],
        unique=False,
    )
    op.create_table(
        "employees",
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employees_external_id"),
        "employees",
        ["external_id"],
        unique=True,
    )
    op.create_index(op.f("ix_employees_id"), "employees", ["id"], unique=False)
    op.create_index(op.f("ix_employees_name"), "employees", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employees_name"), table_name="employees")
    op.drop_index(op.f("ix_employees_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_external_id"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_distributors_name"), table_name="distributors")
    op.drop_index(op.f("ix_distributors_id"), table_name="distributors")
    op.drop_index(op.f("ix_distributors_external_id"), table_name="distributors")
    op.drop_table("distributors")
    op.drop_index(op.f("ix_advisers_name"), table_name="advisers")
    op.drop_index(op.f("ix_advisers_id"), table_name="advisers")
    op.drop_index(op.f("ix_advisers_external_id"), table_name="advisers")
    op.drop_table("advisers")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_id"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_dummy_model_name"), table_name="dummy_model")
    op.drop_index(op.f("ix_dummy_model_id"), table_name="dummy_model")
    op.drop_table("dummy_model")
    # ### end Alembic commands ###
