"""Add SchemeNAV model

Revision ID: 9950efa20a3c
Revises: 46b099781315
Create Date: 2024-03-19 12:34:10.762425

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9950efa20a3c"
down_revision = "46b099781315"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheme_nav",
        sa.Column("scheme_id", sa.UUID(), nullable=False),
        sa.Column("nav_data", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["scheme_id"], ["mutual_fund_schemes.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scheme_nav_id"), "scheme_nav", ["id"], unique=False)
    op.create_index(
        op.f("ix_scheme_nav_scheme_id"),
        "scheme_nav",
        ["scheme_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheme_nav_scheme_id"), table_name="scheme_nav")
    op.drop_index(op.f("ix_scheme_nav_id"), table_name="scheme_nav")
    op.drop_table("scheme_nav")
    # ### end Alembic commands ###
