"""Add AMC and MutualFundScheme model

Revision ID: ead4e833698f
Revises: c21a2285ca5c
Create Date: 2024-01-10 12:55:51.384065

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ead4e833698f"
down_revision = "c21a2285ca5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amcs",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_amcs_id"), "amcs", ["id"], unique=False)
    op.create_index(op.f("ix_amcs_name"), "amcs", ["name"], unique=True)
    op.create_table(
        "mutual_fund_schemes",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("amc_id", sa.UUID(), nullable=True),
        sa.Column("scheme_plan", sa.String(length=50), nullable=False),
        sa.Column("scheme_type", sa.String(length=200), nullable=False),
        sa.Column("scheme_category", sa.String(length=200), nullable=False),
        sa.Column("nav", sa.Float(), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=False),
        sa.Column("cagr", sa.Float(), nullable=True),
        sa.Column("risk_level", sa.String(length=50), nullable=False),
        sa.Column("aum", sa.Float(), nullable=False),
        sa.Column("ter", sa.Float(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("benchmark_index", sa.String(length=200), nullable=False),
        sa.Column("min_investment_sip", sa.Float(), nullable=False),
        sa.Column("min_investment_one_time", sa.Float(), nullable=False),
        sa.Column("exit_load", sa.String(length=200), nullable=False),
        sa.Column("fund_manager", sa.String(length=200), nullable=False),
        sa.Column("return_since_inception", sa.Float(), nullable=False),
        sa.Column("return_last_year", sa.Float(), nullable=False),
        sa.Column("return_last3_years", sa.Float(), nullable=False),
        sa.Column("return_last5_years", sa.Float(), nullable=False),
        sa.Column("standard_deviation", sa.Float(), nullable=True),
        sa.Column("sharpe_ratio", sa.Float(), nullable=True),
        sa.Column("sortino_ratio", sa.Float(), nullable=True),
        sa.Column("alpha", sa.Float(), nullable=True),
        sa.Column("beta", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["amc_id"], ["amcs.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isin"),
    )
    op.create_index(
        op.f("ix_mutual_fund_schemes_id"),
        "mutual_fund_schemes",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mutual_fund_schemes_name"),
        "mutual_fund_schemes",
        ["name"],
        unique=True,
    )
    op.alter_column(
        "advisers",
        "organization_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.alter_column(
        "distributors",
        "organization_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.alter_column(
        "employees",
        "organization_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees",
        "organization_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        "distributors",
        "organization_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        "advisers",
        "organization_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.drop_index(op.f("ix_mutual_fund_schemes_name"), table_name="mutual_fund_schemes")
    op.drop_index(op.f("ix_mutual_fund_schemes_id"), table_name="mutual_fund_schemes")
    op.drop_table("mutual_fund_schemes")
    op.drop_index(op.f("ix_amcs_name"), table_name="amcs")
    op.drop_index(op.f("ix_amcs_id"), table_name="amcs")
    op.drop_table("amcs")
    # ### end Alembic commands ###
