"""update in portfolio model

Revision ID: 46b099781315
Revises: 4e8e3d78300c
Create Date: 2024-03-08 11:35:56.566960

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "46b099781315"
down_revision = "4e8e3d78300c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "portfolios",
        sa.Column("index_fund_proportion", sa.Integer(), nullable=True),
    )
    op.add_column(
        "portfolios",
        sa.Column("other_proportion", sa.Integer(), nullable=True),
    )
    op.add_column("portfolios", sa.Column("logo", sa.String(), nullable=True))
    op.add_column(
        "portfolios",
        sa.Column("three_month_return", sa.Float(), nullable=True),
    )
    op.add_column(
        "portfolios",
        sa.Column("six_month_return", sa.Float(), nullable=True),
    )
    op.add_column("portfolios", sa.Column("one_year_return", sa.Float(), nullable=True))
    op.add_column(
        "portfolios",
        sa.Column("three_year_return", sa.Float(), nullable=True),
    )
    op.add_column(
        "portfolios",
        sa.Column("five_year_return", sa.Float(), nullable=True),
    )
    op.alter_column(
        "portfolios",
        "equity_proportion",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "portfolios",
        "debt_proportion",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "portfolios",
        "hybrid_proportion",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "portfolios",
        "gold_proportion",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "portfolios",
        "gold_proportion",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "portfolios",
        "hybrid_proportion",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "portfolios",
        "debt_proportion",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "portfolios",
        "equity_proportion",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_column("portfolios", "five_year_return")
    op.drop_column("portfolios", "three_year_return")
    op.drop_column("portfolios", "one_year_return")
    op.drop_column("portfolios", "six_month_return")
    op.drop_column("portfolios", "three_month_return")
    op.drop_column("portfolios", "logo")
    op.drop_column("portfolios", "other_proportion")
    op.drop_column("portfolios", "index_fund_proportion")
    # ### end Alembic commands ###
