"""Add portfolio model

Revision ID: 4e8e3d78300c
Revises: ead4e833698f
Create Date: 2024-02-15 04:24:01.491342

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4e8e3d78300c"
down_revision = "ead4e833698f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolios",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("adviser_id", sa.UUID(), nullable=True),
        sa.Column("risk_level", sa.String(), nullable=False),
        sa.Column("equity_proportion", sa.Integer(), nullable=False),
        sa.Column("debt_proportion", sa.Integer(), nullable=False),
        sa.Column("hybrid_proportion", sa.Integer(), nullable=False),
        sa.Column("gold_proportion", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["adviser_id"], ["advisers.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_portfolios_id"), "portfolios", ["id"], unique=False)
    op.create_table(
        "portfolio_mutualfundscheme",
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("mutualfundscheme_id", sa.UUID(), nullable=False),
        sa.Column("proportion", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["mutualfundscheme_id"], ["mutual_fund_schemes.id"]),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"]),
        sa.PrimaryKeyConstraint("portfolio_id", "mutualfundscheme_id", "id"),
    )
    op.create_index(
        op.f("ix_portfolio_mutualfundscheme_id"),
        "portfolio_mutualfundscheme",
        ["id"],
        unique=False,
    )
    op.add_column("amcs", sa.Column("code", sa.String(length=200), nullable=False))
    op.add_column("amcs", sa.Column("fund_name", sa.String(length=200), nullable=False))
    op.add_column("amcs", sa.Column("email", sa.String(length=200), nullable=False))
    op.add_column("amcs", sa.Column("phone", sa.String(length=200), nullable=False))
    op.add_column("amcs", sa.Column("address", sa.String(length=200), nullable=False))
    op.add_column("amcs", sa.Column("website", sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("amcs", "website")
    op.drop_column("amcs", "address")
    op.drop_column("amcs", "phone")
    op.drop_column("amcs", "email")
    op.drop_column("amcs", "fund_name")
    op.drop_column("amcs", "code")
    op.drop_index(
        op.f("ix_portfolio_mutualfundscheme_id"),
        table_name="portfolio_mutualfundscheme",
    )
    op.drop_table("portfolio_mutualfundscheme")
    op.drop_index(op.f("ix_portfolios_id"), table_name="portfolios")
    op.drop_table("portfolios")
    # ### end Alembic commands ###
